apt-get = ["build-essential", "curl", "git", "gawk", "wget", "unzip", "autoconf", "automake", "cmake", "tmux", "openssh-server", "openssh-client", "httpie", "code", "neofetch", "stow"]
"ble.sh" = true
zoxide = true
tailscale = true
neofetch = true
doppler = true

[stow]
git = "github:tsirysndr/android-dotfiles"

[mise]
node = "latest"

[pkgx]
eza = "latest"
zellij = "latest"
rg = "latest"
jq = "latest"
gh = "latest"
fzf = "latest"
glow = "latest"
tig = "latest"
"neovim.io" = "latest"
gleam = "latest"
zig = "latest"

[curl]
bun = "https://bun.sh/install"
deno = "https://deno.land/install.sh"
pkgx = "https://pkgx.sh"
oh-my-posh = "https://ohmyposh.dev/install.sh"
atuin = "https://setup.atuin.sh"

[npm]
"@anthropic-ai/claude-code" = "latest"
"@google/gemini-cli" = "latest"

[oh_my_posh]
theme = "tokyonight_storm"

[alias]
ls = "eza -lh"

[ssh]
port = 22
authorized_keys = ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDjTkQlVM7vr3srk1XNTsJQblYT+GwjzZrBJYVvC5xbTAUPHZBMDgl3SBrhELQTBkKtl6WEKTGTYGfxpEJP94SThyDgoV0r+jTHCAFc1OevtL81Hz8whmM50qZv2VYMqMTrZUmQr6EaZRqNKkGjlKAtK3l7rOhrWYPh0TAt/lL7yVXy3C4m225tpPbwJSL3YT/iGny8kYYpdpS3fGVHRE8XxaSqOA7QjbRSlI2BTBAGmqhxsje0QKbVczajpVY9y5gvDz3f17YAOYqqIcI65XpF2bT5N9HuV7ulvq6OjOI2l82lBMWZ69ZlJKM+6sSbvdB9VEv5+sfTwAovcGLEnv30QImSTRpH7wOPyZoDQHoe5zWFJ2JeN5zhU7hPZbIz5AobZLqLHKVGv4LwnD12eOBXBnO8mNpj35XuTif4SPxzqUhxA3qOkRcndidMX1fbbkDQp4vcEdebyTuRftleolOsXwtOOErRJXZdLRG84c4QRU8detGghz0JTQa0aG0VAts= tsiry.sndr@rocksky.app"]

[nix]


